import uuid
import logging
from app.core.client import supabase  # The client with Service Key
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

# HARDCODED MASTER TEMPLATE ID (JPRS DIGITAL CONNECT)
JPRS_TENANT_ID = "fe0192a0-6e11-4f5e-b6ca-6505d7c1e85e"

async def initialize_organization_permissions(tenant_id: uuid.UUID):
    """
    Clones permissions from JPRS DIGITAL CONNECT to the new tenant_id.
    Uses the Supabase Service Role Key via app.core.client.
    """
    try:
        logger.info(f"🧬 [SERVICE] Starting Permission Cloning for Tenant: {tenant_id}")
        logger.info(f"   > Source Template ID: {JPRS_TENANT_ID}")

        # 1. FETCH SOURCE PERMISSIONS (JPRS)
        # We fetch explicitly 'role', 'module', 'resource', 'action', 'name', 'is_allowed'
        response = supabase.table('role_permissions')\
            .select('role, module, resource, action, name, is_allowed')\
            .eq('tenant_id', JPRS_TENANT_ID)\
            .execute()
            
        source_perms: List[Dict[str, Any]] = response.data
        
        if not source_perms:
            msg = f"❌ CRITICAL: Template JPRS ({JPRS_TENANT_ID}) has 0 permissions. Cannot clone."
            logger.error(msg)
            raise ValueError(msg)
            
        logger.info(f"   > Found {len(source_perms)} permissions in Template.")

        # 2. PREPARE BATCH
        new_perms = []
        for p in source_perms:
            new_perms.append({
                "tenant_id": str(tenant_id), # The new org ID
                "role": str(p['role']).lower(), # FORCE LOWERCASE
                "module": p['module'],
                "resource": p['resource'],
                "action": p['action'],
                "name": p.get('name'),
                "is_allowed": p['is_allowed']
                # 'id' is auto-generated by Supabase/Postgres if not provided, 
                # or we can generate it. Let's let DB default handle it if possible, 
                # but explicit UUID is safer for batch insert in some libs.
                # app.models.core has default=uuid.uuid4, but direct API insert 
                # might need it if the column is NOT defined as default gen_random_uuid().
                # RolePermission model says default=uuid.uuid4 (python side).
                # API Insert checks DB default. Assume DB has default or we provide it.
                # Let's provide it to be safe.
                # "id": str(uuid.uuid4()) 
            })
            
        # 3. INSERT BATCH
        # Supabase API usually handles batch inserts well. 473 items might need chunking?
        # Let's verify batch size limits. Usually 1000 is fine. JPRS is ~473.
        
        insert_res = supabase.table('role_permissions').insert(new_perms).execute()
        
        # Check result
        # insert_res.data contains the inserted rows
        inserted_count = len(insert_res.data) if insert_res.data else 0
        
        logger.info(f"✅ Clonación exitosa: {inserted_count} permisos copiados a {tenant_id}")
        
        if inserted_count == 0:
            raise ValueError("❌ Error: Insert return 0 rows. Cloning failed.")

        return True

    except Exception as e:
        logger.error(f"❌ SERVICE CLONING ERROR: {e}", exc_info=True)
        raise e
