# This file is the SINGLE SOURCE OF TRUTH for system permissions.
ROLES = ['super_admin', 'administrador', 'gerente', 'supervisor_senior', 'supervisor', 'representante', 'auditor_calidad', 'seguimiento', 'digitacion', 'dpto_estadistica', 'cliente']

MASTER_CATALOG = [
    ('config_hub', 'campaigns', 'create', 'Crear Campañas'),
    ('config_hub', 'campaigns', 'delete', 'Eliminar Campañas'),
    ('config_hub', 'campaigns', 'read', 'Ver Campañas'),
    ('config_hub', 'campaigns', 'update', 'Editar Campañas'),
    ('config_hub', 'goals', 'create', 'Crear Objetivos'),
    ('config_hub', 'goals', 'delete', 'Eliminar Objetivos'),
    ('config_hub', 'goals', 'read', 'Ver Objetivos'),
    ('config_hub', 'goals', 'update', 'Editar Objetivos'),
    ('config_hub', 'products', 'create', 'Crear Productos'),
    ('config_hub', 'products', 'delete', 'Eliminar Productos'),
    ('config_hub', 'products', 'read', 'Ver Productos'),
    ('config_hub', 'products', 'update', 'Editar Productos'),
    ('config_hub', 'statuses', 'create', 'Crear Estatus'),
    ('config_hub', 'statuses', 'read', 'Ver Estatus'),
    ('config_hub', 'users', 'create', 'Crear Usuarios'),
    ('config_hub', 'users', 'delete', 'Eliminar Usuarios'),
    ('config_hub', 'users', 'read', 'Ver Usuarios'),
    ('config_hub', 'users', 'update', 'Editar Usuarios'),
    ('dashboard', 'campaigns', 'delete', 'Eliminar Campañas'),
    ('dashboard', 'campaigns', 'export', 'Exportar Campañas'),
    ('dashboard', 'campaigns', 'read', 'Ver Campañas'),
    ('dashboard', 'campaigns', 'write', 'Editar Campañas'),
    ('dashboard', 'goals', 'delete', 'Eliminar Objetivos'),
    ('dashboard', 'goals', 'export', 'Exportar Objetivos'),
    ('dashboard', 'goals', 'read', 'Ver Objetivos'),
    ('dashboard', 'goals', 'write', 'Editar Objetivos'),
    ('dashboard', 'products', 'delete', 'Eliminar Productos'),
    ('dashboard', 'products', 'export', 'Exportar Productos'),
    ('dashboard', 'products', 'read', 'Ver Productos'),
    ('dashboard', 'products', 'write', 'Editar Productos'),
    ('dashboard', 'sales', 'change_status', 'Cambiar Estatus Ventas'),
    ('dashboard', 'sales', 'create', 'Crear Ventas'),
    ('dashboard', 'sales', 'delete', 'Eliminar Ventas'),
    ('dashboard', 'sales', 'export', 'Exportar Ventas'),
    ('dashboard', 'sales', 'read', 'Ver Ventas'),
    ('dashboard', 'sales', 'update', 'Editar Ventas'),
    ('dashboard', 'sales', 'write', 'Editar Ventas'),
    ('dev_modules', 'conversations', 'delete', 'Eliminar Conversaciones'),
    ('dev_modules', 'conversations', 'export', 'Exportar Conversaciones'),
    ('dev_modules', 'conversations', 'read', 'Ver Conversaciones'),
    ('dev_modules', 'conversations', 'write', 'Editar Conversaciones'),
    ('dev_modules', 'evaluations', 'delete', 'Eliminar Evaluaciones'),
    ('dev_modules', 'evaluations', 'export', 'Exportar Evaluaciones'),
    ('dev_modules', 'evaluations', 'read', 'Ver Evaluaciones'),
    ('dev_modules', 'evaluations', 'write', 'Editar Evaluaciones'),
    ('dev_modules', 'history', 'delete', 'Eliminar Historial'),
    ('dev_modules', 'history', 'export', 'Exportar Historial'),
    ('dev_modules', 'history', 'read', 'Ver Historial'),
    ('dev_modules', 'history', 'write', 'Editar Historial'),
    ('dev_modules', 'scorecards', 'delete', 'Eliminar Tableros'),
    ('dev_modules', 'scorecards', 'export', 'Exportar Tableros'),
    ('dev_modules', 'scorecards', 'read', 'Ver Tableros'),
    ('dev_modules', 'scorecards', 'write', 'Editar Tableros'),
    ('finance', 'finance', 'export', 'Exportar Finanzas'),
    ('finance', 'finance', 'payroll', 'Gestionar Nómina Finanzas'),
    ('finance', 'finance', 'read', 'Ver Finanzas'),
    ('finance', 'finance', 'results', 'Ver Resultados Finanzas'),
    ('finance', 'finance', 'summary', 'Ver Resumen Finanzas'),
    ('history', 'sales', 'export_history', 'Exportar Historial Ventas'),
    ('history', 'sales', 'read_history', 'Ver Historial Ventas'),
    ('performance', 'performance', 'backoffice', 'Panel Backoffice Desempeño'),
    ('performance', 'performance', 'efficiency', 'Eficiencia Operativa Desempeño'),
    ('performance', 'performance', 'export', 'Exportar Desempeño'),
    ('performance', 'performance', 'read', 'Ver Desempeño'),
    ('performance', 'performance', 'reports', 'Reportes Especiales Desempeño'),
    ('performance', 'performance', 'scorecard', 'Tablero de Puntuación Desempeño'),
    ('system', 'audit_logs', 'delete', 'Eliminar Logs de Auditoría'),
    ('system', 'audit_logs', 'export', 'Exportar Logs de Auditoría'),
    ('system', 'audit_logs', 'read', 'Ver Logs de Auditoría'),
    ('system', 'audit_logs', 'write', 'Editar Logs de Auditoría'),
    ('system', 'campaigns', 'delete', 'Eliminar Campañas'),
    ('system', 'campaigns', 'read', 'Ver Campañas'),
    ('system', 'campaigns', 'write', 'Editar Campañas'),
    ('system', 'roles_matrix', 'delete', 'Eliminar Matriz de Roles'),
    ('system', 'roles_matrix', 'export', 'Exportar Matriz de Roles'),
    ('system', 'roles_matrix', 'read', 'Ver Matriz de Roles'),
    ('system', 'roles_matrix', 'write', 'Editar Matriz de Roles'),
    ('system', 'users', 'delete', 'Eliminar Usuarios'),
    ('system', 'users', 'export', 'Exportar Usuarios'),
    ('system', 'users', 'read', 'Ver Usuarios'),
    ('system', 'users', 'write', 'Editar Usuarios'),
    ('system_reserved', 'reserved', 'action_1', 'Reserva Técnica 1'),
    ('system_reserved', 'reserved', 'action_10', 'Reserva Técnica 10'),
    ('system_reserved', 'reserved', 'action_11', 'Reserva Técnica 11'),
    ('system_reserved', 'reserved', 'action_12', 'Reserva Técnica 12'),
    ('system_reserved', 'reserved', 'action_2', 'Reserva Técnica 2'),
    ('system_reserved', 'reserved', 'action_3', 'Reserva Técnica 3'),
    ('system_reserved', 'reserved', 'action_4', 'Reserva Técnica 4'),
    ('system_reserved', 'reserved', 'action_5', 'Reserva Técnica 5'),
    ('system_reserved', 'reserved', 'action_6', 'Reserva Técnica 6'),
    ('system_reserved', 'reserved', 'action_7', 'Reserva Técnica 7'),
    ('system_reserved', 'reserved', 'action_8', 'Reserva Técnica 8'),
    ('system_reserved', 'reserved', 'action_9', 'Reserva Técnica 9'),
    ('tournaments', 'tournaments', 'arbitration_panel', 'Panel de Arbitraje Torneos'),
    ('tournaments', 'tournaments', 'create_battle', 'Crear Torneo Torneos'),
    ('tournaments', 'tournaments', 'delete', 'Eliminar Torneos'),
    ('tournaments', 'tournaments', 'edit', 'Editar Torneo Torneos'),
    ('tournaments', 'tournaments', 'view_module', 'Entrar al Módulo: Torneos'),
    ('tournaments', 'tournaments', 'view_race_track', 'Ver Carreras en Vivo Torneos'),
]

DEFAULT_MAPPING = {}
