# This file is the SINGLE SOURCE OF TRUTH for system permissions.
ROLES = ['super_admin', 'administrador', 'gerente', 'supervisor_senior', 'supervisor', 'representante', 'auditor_calidad', 'seguimiento', 'digitacion', 'dpto_estadistica', 'cliente']

MASTER_CATALOG = [
    ('config_hub', 'campaigns', 'create', 'Crear Campañas'),
    ('config_hub', 'campaigns', 'delete', 'Eliminar Campañas'),
    ('config_hub', 'campaigns', 'read', 'Ver Campañas'),
    ('config_hub', 'campaigns', 'update', 'Editar Campañas'),
    ('config_hub', 'goals', 'create', 'Crear Objetivos'),
    ('config_hub', 'goals', 'delete', 'Eliminar Objetivos'),
    ('config_hub', 'goals', 'read', 'Ver Objetivos'),
    ('config_hub', 'goals', 'update', 'Editar Objetivos'),
    ('config_hub', 'products', 'create', 'Crear Productos'),
    ('config_hub', 'products', 'delete', 'Eliminar Productos'),
    ('config_hub', 'products', 'read', 'Ver Productos'),
    ('config_hub', 'products', 'update', 'Editar Productos'),
    ('config_hub', 'statuses', 'create', 'Crear Estatus'),
    ('config_hub', 'statuses', 'read', 'Ver Estatus'),
    ('dashboard', 'sales', 'change_status', 'Cambiar Estatus Ventas'),
    ('dashboard', 'sales', 'create', 'Crear Ventas'),
    ('dashboard', 'sales', 'delete', 'Eliminar Ventas'),
    ('dashboard', 'sales', 'export', 'Exportar Ventas'),
    ('dashboard', 'sales', 'read', 'Ver Ventas'),
    ('dashboard', 'sales', 'update', 'Editar Ventas'),
    ('finance', 'finance', 'export', 'Exportar Finanzas'),
    ('finance', 'finance', 'payroll', 'Gestionar Nómina Finanzas'),
    ('finance', 'finance', 'read', 'Ver Finanzas'),
    ('finance', 'finance', 'results', 'Ver Resultados Finanzas'),
    ('finance', 'finance', 'summary', 'Ver Resumen Finanzas'),
    ('history', 'sales', 'export_history', 'Exportar Historial Ventas'),
    ('history', 'sales', 'read_history', 'Ver Historial Ventas'),
    ('performance', 'performance', 'backoffice', 'Panel Backoffice Desempeño'),
    ('performance', 'performance', 'efficiency', 'Eficiencia Operativa Desempeño'),
    ('performance', 'performance', 'export', 'Exportar Desempeño'),
    ('performance', 'performance', 'read', 'Ver Desempeño'),
    ('performance', 'performance', 'reports', 'Reportes Especiales Desempeño'),
    ('performance', 'performance', 'scorecard', 'Tablero de Puntuación Desempeño'),
    ('system', 'audit_logs', 'delete', 'Eliminar Logs de Auditoría'),
    ('system', 'audit_logs', 'export', 'Exportar Logs de Auditoría'),
    ('system', 'audit_logs', 'read', 'Ver Logs de Auditoría'),
    ('system', 'audit_logs', 'write', 'Editar Logs de Auditoría'),
    ('system', 'roles_matrix', 'delete', 'Eliminar Matriz de Roles'),
    ('system', 'roles_matrix', 'export', 'Exportar Matriz de Roles'),
    ('system', 'roles_matrix', 'read', 'Ver Matriz de Roles'),
    ('system', 'roles_matrix', 'write', 'Editar Matriz de Roles'),
    ('system', 'users', 'create', 'Crear Usuarios'),
    ('system', 'users', 'delete', 'Eliminar Usuarios'),
    ('system', 'users', 'export', 'Exportar Usuarios'),
    ('system', 'users', 'manage', 'Gestionar Seguridad Usuarios'),
    ('system', 'users', 'read', 'Ver Usuarios'),
    ('system', 'users', 'update', 'Editar Usuarios'),
    ('system_reserved', 'reserved', 'action_1', 'Reserva Técnica 1'),
    ('system_reserved', 'reserved', 'action_10', 'Reserva Técnica 10'),
    ('system_reserved', 'reserved', 'action_11', 'Reserva Técnica 11'),
    ('system_reserved', 'reserved', 'action_12', 'Reserva Técnica 12'),
    ('system_reserved', 'reserved', 'action_13', 'Reserva Técnica 13'),
    ('system_reserved', 'reserved', 'action_14', 'Reserva Técnica 14'),
    ('system_reserved', 'reserved', 'action_15', 'Reserva Técnica 15'),
    ('system_reserved', 'reserved', 'action_16', 'Reserva Técnica 16'),
    ('system_reserved', 'reserved', 'action_17', 'Reserva Técnica 17'),
    ('system_reserved', 'reserved', 'action_18', 'Reserva Técnica 18'),
    ('system_reserved', 'reserved', 'action_19', 'Reserva Técnica 19'),
    ('system_reserved', 'reserved', 'action_2', 'Reserva Técnica 2'),
    ('system_reserved', 'reserved', 'action_20', 'Reserva Técnica 20'),
    ('system_reserved', 'reserved', 'action_21', 'Reserva Técnica 21'),
    ('system_reserved', 'reserved', 'action_22', 'Reserva Técnica 22'),
    ('system_reserved', 'reserved', 'action_23', 'Reserva Técnica 23'),
    ('system_reserved', 'reserved', 'action_24', 'Reserva Técnica 24'),
    ('system_reserved', 'reserved', 'action_25', 'Reserva Técnica 25'),
    ('system_reserved', 'reserved', 'action_26', 'Reserva Técnica 26'),
    ('system_reserved', 'reserved', 'action_27', 'Reserva Técnica 27'),
    ('system_reserved', 'reserved', 'action_28', 'Reserva Técnica 28'),
    ('system_reserved', 'reserved', 'action_29', 'Reserva Técnica 29'),
    ('system_reserved', 'reserved', 'action_3', 'Reserva Técnica 3'),
    ('system_reserved', 'reserved', 'action_30', 'Reserva Técnica 30'),
    ('system_reserved', 'reserved', 'action_31', 'Reserva Técnica 31'),
    ('system_reserved', 'reserved', 'action_32', 'Reserva Técnica 32'),
    ('system_reserved', 'reserved', 'action_33', 'Reserva Técnica 33'),
    ('system_reserved', 'reserved', 'action_34', 'Reserva Técnica 34'),
    ('system_reserved', 'reserved', 'action_35', 'Reserva Técnica 35'),
    ('system_reserved', 'reserved', 'action_36', 'Reserva Técnica 36'),
    ('system_reserved', 'reserved', 'action_37', 'Reserva Técnica 37'),
    ('system_reserved', 'reserved', 'action_38', 'Reserva Técnica 38'),
    ('system_reserved', 'reserved', 'action_39', 'Reserva Técnica 39'),
    ('system_reserved', 'reserved', 'action_4', 'Reserva Técnica 4'),
    ('system_reserved', 'reserved', 'action_40', 'Reserva Técnica 40'),
    ('system_reserved', 'reserved', 'action_41', 'Reserva Técnica 41'),
    ('system_reserved', 'reserved', 'action_42', 'Reserva Técnica 42'),
    ('system_reserved', 'reserved', 'action_43', 'Reserva Técnica 43'),
    ('system_reserved', 'reserved', 'action_44', 'Reserva Técnica 44'),
    ('system_reserved', 'reserved', 'action_45', 'Reserva Técnica 45'),
    ('system_reserved', 'reserved', 'action_46', 'Reserva Técnica 46'),
    ('system_reserved', 'reserved', 'action_5', 'Reserva Técnica 5'),
    ('system_reserved', 'reserved', 'action_6', 'Reserva Técnica 6'),
    ('system_reserved', 'reserved', 'action_7', 'Reserva Técnica 7'),
    ('system_reserved', 'reserved', 'action_8', 'Reserva Técnica 8'),
    ('system_reserved', 'reserved', 'action_9', 'Reserva Técnica 9'),
    ('tournaments', 'tournaments', 'arbitration_panel', 'Panel de Arbitraje Torneos'),
    ('tournaments', 'tournaments', 'create_battle', 'Crear Torneo Torneos'),
    ('tournaments', 'tournaments', 'delete', 'Eliminar Torneos'),
    ('tournaments', 'tournaments', 'edit', 'Editar Torneo Torneos'),
    ('tournaments', 'tournaments', 'view_module', 'Entrar al Módulo: Torneos'),
    ('tournaments', 'tournaments', 'view_race_track', 'Ver Carreras en Vivo Torneos'),
]

DEFAULT_MAPPING = {}
