# This file is auto-generated from jprs_matrix.json
# It serves as the master source for all system permissions.

ROLES = ['Supervisor Senior', 'Gerente', 'Supervisor', 'Administrador', 'Representante', 'Super Admin', 'Cliente', 'Dpto Estadistica', 'Auditor Calidad', 'Seguimiento', 'Digitación']

MASTER_CATALOG = [
    ('config_campaigns', 'campaigns', 'create', 'Crear Campañas'),
    ('config_campaigns', 'campaigns', 'delete', 'Eliminar Campañas'),
    ('config_campaigns', 'campaigns', 'read', 'Ver Campañas'),
    ('config_campaigns', 'campaigns', 'update', 'Actualizar Campañas'),
    ('config_goals', 'goals', 'create', 'Crear Metas'),
    ('config_goals', 'goals', 'delete', 'Eliminar Metas'),
    ('config_goals', 'goals', 'read', 'Ver Metas'),
    ('config_goals', 'goals', 'update', 'Actualizar Metas'),
    ('config_products', 'products', 'create', 'Crear Productos'),
    ('config_products', 'products', 'delete', 'Eliminar Productos'),
    ('config_products', 'products', 'read', 'Ver Productos'),
    ('config_products', 'products', 'update', 'Actualizar Productos'),
    ('config_statuses', 'statuses', 'create', 'Crear Estados'),
    ('config_statuses', 'statuses', 'read', 'Ver Estados'),
    ('config_users', 'users', 'create', 'Crear Usuarios'),
    ('config_users', 'users', 'delete', 'Eliminar Usuarios'),
    ('config_users', 'users', 'read', 'Ver Usuarios'),
    ('config_users', 'users', 'update', 'Editar Usuarios'),
    ('dashboard', 'sales', 'change_status', 'Cambiar Estatus'),
    ('dashboard', 'sales', 'create', 'Botón Nueva Venta'),
    ('dashboard', 'sales', 'delete', 'Eliminar Venta'),
    ('dashboard', 'sales', 'export', 'Exportar Data Dashboard'),
    ('dashboard', 'sales', 'read', 'Ver Dashboard de Ventas'),
    ('dashboard', 'sales', 'update', 'Editar Venta'),
    ('finance', 'finance', 'export', 'Exportar Data Financiera'),
    ('finance', 'finance', 'payroll', 'Ver Nómina de Comisiones'),
    ('finance', 'finance', 'read', 'Ver Pestaña Finanzas'),
    ('finance', 'finance', 'results', 'Ver Resultados Financieros'),
    ('finance', 'finance', 'summary', 'Ver Resumen Financiero'),
    ('history', 'sales', 'export_history', 'Exportar Historial'),
    ('history', 'sales', 'read_history', 'Ver Historial de Ventas'),
    ('performance', 'performance', 'backoffice', 'Ver Backoffice'),
    ('performance', 'performance', 'efficiency', 'Ver Eficiencia Operativa'),
    ('performance', 'performance', 'export', 'Exportar Data Performance'),
    ('performance', 'performance', 'read', 'Ver Pestaña Performance'),
    ('performance', 'performance', 'reports', 'Generar Reportes Performance'),
    ('performance', 'performance', 'scorecard', 'Ver Scorecard'),
    ('tournaments', 'tournaments', 'arbitration_panel', 'Panel de Arbitraje'),
    ('tournaments', 'tournaments', 'create_battle', 'Botón Crear Torneo'),
    ('tournaments', 'tournaments', 'delete', 'Borrar Torneo'),
    ('tournaments', 'tournaments', 'edit', 'Editar Torneo'),
    ('tournaments', 'tournaments', 'live_positions', 'Ver Posiciones en Vivo'),
    ('tournaments', 'tournaments', 'view_module', 'Entrar a Torneos'),
    ('tournaments', 'tournaments', 'view_race_track', 'Ver Carreras Activas'),
]

# Default is_allowed mapping for each role
DEFAULT_MAPPING = {
    'Supervisor Senior': {
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Gerente': {
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Supervisor': {
        ('config_products', 'products', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Administrador': {
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): True,
    },
    'Representante': {
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Super Admin': {
        ('dashboard', 'sales', 'read'): True,
        ('dashboard', 'sales', 'create'): True,
        ('dashboard', 'sales', 'update'): True,
        ('dashboard', 'sales', 'delete'): True,
        ('dashboard', 'sales', 'change_status'): True,
        ('dashboard', 'sales', 'export'): True,
        ('history', 'sales', 'read_history'): True,
        ('history', 'sales', 'export_history'): True,
        ('performance', 'performance', 'read'): True,
        ('performance', 'performance', 'efficiency'): True,
        ('performance', 'performance', 'scorecard'): True,
        ('performance', 'performance', 'backoffice'): True,
        ('performance', 'performance', 'reports'): True,
        ('performance', 'performance', 'export'): True,
        ('finance', 'finance', 'read'): True,
        ('finance', 'finance', 'results'): True,
        ('finance', 'finance', 'summary'): True,
        ('finance', 'finance', 'payroll'): True,
        ('finance', 'finance', 'export'): True,
        ('config_campaigns', 'campaigns', 'read'): True,
        ('config_campaigns', 'campaigns', 'create'): True,
        ('config_campaigns', 'campaigns', 'update'): True,
        ('config_campaigns', 'campaigns', 'delete'): True,
        ('config_products', 'products', 'read'): True,
        ('config_products', 'products', 'create'): True,
        ('config_products', 'products', 'update'): True,
        ('config_products', 'products', 'delete'): True,
        ('config_goals', 'goals', 'read'): True,
        ('config_goals', 'goals', 'create'): True,
        ('config_goals', 'goals', 'update'): True,
        ('config_goals', 'goals', 'delete'): True,
        ('config_statuses', 'statuses', 'read'): True,
        ('config_statuses', 'statuses', 'create'): True,
        ('config_users', 'users', 'read'): True,
        ('config_users', 'users', 'create'): True,
        ('config_users', 'users', 'update'): True,
        ('config_users', 'users', 'delete'): True,
        ('tournaments', 'tournaments', 'view_module'): True,
        ('tournaments', 'tournaments', 'create_battle'): True,
        ('tournaments', 'tournaments', 'view_race_track'): True,
        ('tournaments', 'tournaments', 'arbitration_panel'): True,
        ('tournaments', 'tournaments', 'edit'): True,
        ('tournaments', 'tournaments', 'delete'): True,
        ('tournaments', 'tournaments', 'live_positions'): True,
    },
    'Cliente': {
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Dpto Estadistica': {
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Auditor Calidad': {
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Seguimiento': {
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
    'Digitación': {
        ('dashboard', 'sales', 'read'): False,
        ('dashboard', 'sales', 'create'): False,
        ('dashboard', 'sales', 'update'): False,
        ('dashboard', 'sales', 'delete'): False,
        ('dashboard', 'sales', 'change_status'): False,
        ('dashboard', 'sales', 'export'): False,
        ('history', 'sales', 'read_history'): False,
        ('history', 'sales', 'export_history'): False,
        ('performance', 'performance', 'read'): False,
        ('performance', 'performance', 'efficiency'): False,
        ('performance', 'performance', 'scorecard'): False,
        ('performance', 'performance', 'backoffice'): False,
        ('performance', 'performance', 'reports'): False,
        ('performance', 'performance', 'export'): False,
        ('finance', 'finance', 'read'): False,
        ('finance', 'finance', 'results'): False,
        ('finance', 'finance', 'summary'): False,
        ('finance', 'finance', 'payroll'): False,
        ('finance', 'finance', 'export'): False,
        ('config_campaigns', 'campaigns', 'read'): False,
        ('config_campaigns', 'campaigns', 'create'): False,
        ('config_campaigns', 'campaigns', 'update'): False,
        ('config_campaigns', 'campaigns', 'delete'): False,
        ('config_products', 'products', 'read'): False,
        ('config_products', 'products', 'create'): False,
        ('config_products', 'products', 'update'): False,
        ('config_products', 'products', 'delete'): False,
        ('config_goals', 'goals', 'read'): False,
        ('config_goals', 'goals', 'create'): False,
        ('config_goals', 'goals', 'update'): False,
        ('config_goals', 'goals', 'delete'): False,
        ('config_statuses', 'statuses', 'read'): False,
        ('config_statuses', 'statuses', 'create'): False,
        ('config_users', 'users', 'read'): False,
        ('config_users', 'users', 'create'): False,
        ('config_users', 'users', 'update'): False,
        ('config_users', 'users', 'delete'): False,
        ('tournaments', 'tournaments', 'view_module'): False,
        ('tournaments', 'tournaments', 'create_battle'): False,
        ('tournaments', 'tournaments', 'view_race_track'): False,
        ('tournaments', 'tournaments', 'arbitration_panel'): False,
        ('tournaments', 'tournaments', 'edit'): False,
        ('tournaments', 'tournaments', 'delete'): False,
        ('tournaments', 'tournaments', 'live_positions'): False,
    },
}
